### ISSUE TITLE
wire: `go get`-ing the wire cmd fails inside of a go module

### ISSUE THREAD

**Issue by drewolson** [google/go-cloud#235]
```
$ go version
go version go1.11beta2 linux/amd64
~$ mkdir example
~$ cd example 
~/example$ echo "module example" > go.mod
~/example$ go get github.com/google/go-cloud/wire/cmd/wire
go: finding github.com/google/go-cloud/wire/cmd/wire latest
go: finding github.com/google/go-cloud/wire/cmd latest
go: finding github.com/google/go-cloud/wire latest
go get github.com/google/go-cloud/wire/cmd/wire: cannot find module providing package github.com/google/go-cloud/wire/cmd/wire
~/example$ which wire
wire not found
```

**Comment by zombiezen** [comment]
@rsc is this expected? Is there a simple way we can instruct people to install binaries with `go get` with the new modules support?

**Comment by rsc** [comment]
This is a bug. go get of binaries is supposed to work.

**Comment by rsc** [comment]
Well maybe not our bug though. The latest tagged version of github.com/google/go-cloud is v0.1.0 and that version did not have a wire/cmd/wire. It had a wire/cmd/gowire. If you tag a new version it should start working.

**Comment by zombiezen** [comment]
Thanks Russ! I'll cut a new release.

**Comment by zombiezen** [comment]
v0.1.1 has been released with the rename and various bug fixes made since initial launch.

**Comment by drewolson** [comment]
This is still an issue for me with the move recent release:

```
~/test$ go version
go version go1.11beta2 linux/amd64
~$ mkdir test
~$ cd test 
~/test$ echo "module test" > go.mod
~/test$ go get github.com/google/go-cloud/wire/cmd/wire
go: finding github.com/google/go-cloud/wire/cmd/wire latest
go: finding github.com/google/go-cloud/wire/cmd latest
go: finding github.com/google/go-cloud/wire latest
go get github.com/google/go-cloud/wire/cmd/wire: missing module for import: github.com/google/go-cloud@v0.1.1 provides github.com/google/go-cloud/wire/cmd/wire
~/test$ which wire
wire not found
```

**Comment by drewolson** [comment]
Scratch that, this does work with `1.11rc1`:

```
~$ go version
go version go1.11rc1 darwin/amd64
~$ mkdir test
~$ cd test 
~/test$ echo "module test" > go.mod
~/test$ go get github.com/google/go-cloud/wire/cmd/wire
go: finding github.com/google/go-cloud/wire/cmd/wire latest
go: finding github.com/google/go-cloud/wire/cmd latest
go: finding github.com/google/go-cloud/wire latest
go: finding github.com/google/go-cloud v0.1.1
go: downloading github.com/google/go-cloud v0.1.1
go: finding github.com/pquerna/ffjson v0.0.0-20180717144149-af8b230fcd20
go: finding github.com/Jeffail/gabs v0.0.0-20180420203615-7a0fed31069a
go: finding github.com/mailru/easyjson v0.0.0-20180723221831-d5012789d665
go: downloading golang.org/x/tools v0.0.0-20180314180217-d853e8088c62
andolson:~/test$ which wire
/Users/<me>/go/bin/wire
```
